# Generated by Django 6.0.1 on 2026-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whalealert',
            name='alert_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='alert_timestamp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='alert_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='amount_full',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='emoticons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='fee_usd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='icon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='receiver_address_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='receiver_amount_usd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='sender_address_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='sender_amount_usd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='social_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='timestamp_utc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='transaction_hash_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whalealert',
            name='tx_card_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
