# Generated by Django 6.0.1 on 2026-03-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_whalealert_alert_text_whalealert_alert_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icoproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='icoproject',
            name='discord',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icoproject',
            name='last_updated',
            field=models.TextField(blank=True, help_text='e.g. March 2, 2026, 17:21', null=True),
        ),
        migrations.AddField(
            model_name='icoproject',
            name='pre_valuation',
            field=models.TextField(blank=True, help_text='Pre-valuation display text', null=True),
        ),
        migrations.AddField(
            model_name='icoproject',
            name='rounds_count',
            field=models.TextField(blank=True, help_text='e.g. In 1 rounds', null=True),
        ),
        migrations.AddField(
            model_name='icoproject',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icoproject',
            name='ticker',
            field=models.CharField(blank=True, help_text='Token ticker e.g. KAT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='icoproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='icoproject',
            name='category_name',
            field=models.TextField(blank=True, help_text='e.g. #230 in Blockchain', null=True),
        ),
        migrations.AlterField(
            model_name='icoproject',
            name='main_img',
            field=models.TextField(blank=True, help_text='Project avatar/cover image URL', null=True),
        ),
        migrations.AlterField(
            model_name='icoproject',
            name='name',
            field=models.TextField(help_text='Project name e.g. Katana'),
        ),
        migrations.AlterField(
            model_name='icoproject',
            name='project_type',
            field=models.TextField(blank=True, help_text='#230 in Blockchain', null=True),
        ),
        migrations.AlterField(
            model_name='icoproject',
            name='raised_text',
            field=models.TextField(blank=True, help_text='Total raised display text e.g. $5M or —', null=True),
        ),
        migrations.AlterField(
            model_name='icoproject',
            name='status',
            field=models.CharField(default='active', help_text='active / upcoming / ended', max_length=50),
        ),
        migrations.AlterField(
            model_name='icoproject',
            name='status_time',
            field=models.TextField(blank=True, help_text='e.g. Active 8d left', null=True),
        ),
    ]
