# Generated by Django 6.0.1 on 2026-03-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_alter_icoproject_options_icoproject_discord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnews',
            name='discription_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='allnews',
            name='discription_main_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='allnews',
            name='title_ar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
